### ISSUE TITLE
Make the sync interval configurable via conf.json

### ISSUE THREAD

**Issue by tanius** [edgeryders/dynalist_notify#19]
The current interval for checking the Dynalist file for new changes is 10 minutes. To allow to adapt this to the requirements of an installation, this should be transformed into a parameter in `conf.json` with a default value of 10 minutes. (Or maybe better, 30 minutes. Better we keep defaults very easy on the servers.)

This way, people can adapt the setting to prevent unnecessary load on the Dynalist API.

**Comment by anuzement** [comment]
We have implemented fetch jobs with cron, so we do not need sync interval.
