### ISSUE TITLE
Fix the syntax error in notify.py

### ISSUE THREAD

**Issue by tanius** [edgeryders/dynalist_notify#4]
Currently, trying to start the `notify.py` script with `python notify.py` will result in the following error message:

    File "notify.py", line 102
    self.sendmail('[Dynalist Notification New Task]', email, f'Hi {res1.group(1)},\nYou have been assigned with new task.\n\n{line}\nGood luck.:)')
                                                                                                                                                 ^
    SyntaxError: invalid syntax

Should be fixed :) See how it pinpoints the error location with the `^` in the line below it.

**Comment by anuzement** [comment]
f-string is introduced in python 3.6. Need update of python version from 2.7

**Comment by tanius** [comment]
Ah that solves it. It was not 2.7, but 3.5.2.

Ok, I'll update the installation requirements :)
